import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { ClipboardCheck, BarChart3, Target } from "lucide-react";
export default function Features() {
    return (_jsx("section", { className: "py-16 md:py-24", children: _jsxs("div", { className: "container mx-auto px-4 md:px-6", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, className: "text-center mb-12 md:mb-16", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-white mb-4", children: "Our Platform Features" }), _jsx("p", { className: "text-lg md:text-xl text-gray-300 max-w-2xl mx-auto px-4", children: "Discover how our platform revolutionizes the way people interact with businesses and earn rewards." })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-12", children: [_jsx(FeatureBlock, { icon: _jsx(ClipboardCheck, { className: "w-16 h-16 text-purple-500" }), title: "Verified Reviews", description: "Leave Authentic Reviews, Verified with ZK Proofs and Location Data.", delay: 0.3 }), _jsx(FeatureBlock, { icon: _jsx(BarChart3, { className: "w-16 h-16 text-pink-500" }), title: "Business Surveys", description: "Create personalized google forms and surveys in seconds", delay: 0.5 }), _jsx(FeatureBlock, { icon: _jsx(Target, { className: "w-16 h-16 text-blue-500" }), title: "Data Labeling", description: "Help train AI models by solving captchas and labeling data", delay: 0.7 })] })] }) }));
}
function FeatureBlock({ icon, title, description, delay }) {
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, transition: { delay, duration: 0.8 }, className: "text-center p-6 md:p-8 rounded-2xl bg-white/10 backdrop-blur-sm", children: [_jsx("div", { className: "flex justify-center mb-4 md:mb-6", children: icon }), _jsx("h3", { className: "text-xl md:text-2xl font-semibold text-white mb-3 md:mb-4", children: title }), _jsx("p", { className: "text-sm md:text-base text-gray-300", children: description })] }));
}
