[package]
name = "fungible_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = '8da516e736ab6f2933d5f7bc6aded99b276035e5891ad75038b21a87b770533e'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "testnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
